### ISSUE TITLE
Importing DXF in CLI mode outputs broken graph file

### ISSUE THREAD

**Issue by tomas-polach** [SpaceGroupUCL/depthmapX#104]
First of all: Thanks for providing this awesome open source software!

This is probably a stupid question and I might just be overlooking something, but:
When importing a DXF file in CLI mode, the resulting new graph file seems to be broken. Further processing is not possible.

Steps to reproduce:
1. Input: `office.dxf`, 14KB -> [office.zip](https://github.com/SpaceGroupUCL/depthmapX/files/1573691/office.zip)
2. CLI: `./depthmapXcli_linux64 -f office.dxf -o out.graph -m IMPORT`
3. Output: `out.graph`, 0.3KB -> [out.zip](https://github.com/SpaceGroupUCL/depthmapX/files/1573699/out.zip)
4. Opening `out.graph` in GUI mode results in a crash

Note: 
Importing `office.dxf` in GUI mode works fine:
<img width="1019" alt="vrn__running_" src="https://user-images.githubusercontent.com/6619499/34185223-75c881e8-e524-11e7-8601-4067e16700c8.png">

I tried on Linux and OSX. Any help would be highly appreciated.

**Comment by frederic-schwarz** [comment]
I discovered the same thing.
What works is
- importing the dxf in GUI mode and saving the graph file
- doing further processing in cli mode 
but that's not a real solution

the dxf from the example also does not import properly with `./depthmapXcli -f gallery.dxf -o out.graph -m IMPORT`
http://archtech.gr/varoudis/depthmapX/LearningMaterial/gallery.dxf

**Comment by orange-vertex** [comment]
Hmm, indeed I forgot to make the code check for that file-extension. I have submitted a new pull request (https://github.com/SpaceGroupUCL/depthmapX/pull/105) that addresses the issue so it will be fixed in the new release!

**Comment by tomas-polach** [comment]
Wow! That was fast! Thank you!
