### ISSUE TITLE
Help links are broken

### ISSUE THREAD

**Issue by esnahn** [SpaceGroupUCL/depthmapX#11]
Under 'Help' menu,

'Get the PDF Handbook' http://www.vr.ucl.ac.uk/depthmap/depthmap4r1.pdf
'Online Tutorials' http://www.vr.ucl.ac.uk/depthmap/tutorials/
'Online Scripting Manual' http://www.vr.ucl.ac.uk/depthmap/scripting/

These links are broken.

**Comment by varoudis** [comment]
all tutorial are accessible via: http://varoudis.github.io/depthmapX/
