### ISSUE TITLE
Incorrect export of "Visibility Graph Connections as CSV"

### ISSUE THREAD

**Issue by SZ-whf** [SpaceGroupUCL/depthmapX#124]
The DepthmapX_0.6 allows to export visibility graph connections for every cell (Map -> Export -> Visibility Graph Connections as CSV). However, the export is incomplete in two situations: (1). some cells (as column "RefFrom") are missing from the export; (2). not all the connections (as column "RefTo) of a cell are exported.

**Comment by orange-vertex** [comment]
Hi SZ-whf,

Given that the graphs created by depthmapX are undirected, the export does not provide both connections if two cells are inter-visible, to reduce the size of the exported file. It only provides the connection from the smallest Ref to the largest Ref.

If this is not what you are referring to, please provide an example graph file, the exported csv from that graph file as well as the list of some of the connections missing.
