### ISSUE TITLE
isovist properties cannot be calculated in DepthmapX 026b

### ISSUE THREAD

**Issue by irohloff** [SpaceGroupUCL/depthmapX#13]
DepthmapX 0.26b doesn't calculate point isovist properties (other than isovist area) and and provide them in Attributes. It was suggested that I should go into settings/preferences and check 'simple version' off. First of all there is no "settings/preferences" menu, but there is "options" under "Tools" menu. I checked simple version off there but it remains checked and I still cannot obtain isovist properties other than isovist area. 

I also still have Depthmap 10.14.00b version in my computer and that one calculates the isovist properties and provide the measures in Attributes. 

Can you fix that problem in depthmapX 026b?

Thanks, 
Ipek

**Comment by 1122mAH** [comment]
Never found the "simple vesrion" hidden in the options,very helpful!
