### ISSUE TITLE
How Depthmap calculate integration

### ISSUE THREAD

**Issue by taribowest** [SpaceGroupUCL/depthmapX#130]
Hi, I'm trying to understand how depthmap calculate integration value. Someone could help me please? Thank you

**Comment by blsemo** [comment]
Hi,

depthmapX issues are for tracking issues with the actual software. For questions on calculation or meaning if measures, it's better to ask on the depthmap (depthmap@jiscmail.ac.uk) or space syntax (spacesyntax@jiscmail.ac.uk) mailing lists.

Cf https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=DEPTHMAP or 
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=spacesyntax for history or joining these lists.

Thanks,
Christian


On 24 February 2018 18:03:16 GMT, taribowest <notifications@github.com> wrote:
>Hi, I'm trying to understand how depthmap calculate integration value.
>Someone could help me please? Thank you
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SpaceGroupUCL/depthmapX/issues/130

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
