### ISSUE TITLE
Can't open graqph files - Depthmapx 0.5 windows

### ISSUE THREAD

**Issue by febalestro** [SpaceGroupUCL/depthmapX#196]
Hello,

I've been experiencing an issue and would like to know if anyone has experienced it before and was able to solve it.
I am using depthmapx 0.5 for windows and i haven't been able to open my graph files (processed). I have attached a print of the error message I get:

![capturar](https://user-images.githubusercontent.com/39524154/40364640-3da24224-5da9-11e8-85cc-6f88d5eabd6f.PNG)

I have tried to solve this issue by downloading other versions of the software, by placing the files on the sime folder as the software and by placing everything on the desktop, all withount success.

Any ideas?
Thank you all in advance :)

**Comment by orange-vertex** [comment]
Hi there,

A few thoughts:
1. depthmapX 0.5 is an old version, please use the latest version from [the releases page](https://github.com/SpaceGroupUCL/depthmapX/releases)
2. Make sure that the graph file and its location only has ASCII characters (the english alphabet) and that there are no spaces in its name or its location. The easiest way to test this is to name your file my.graph and place it in C:\ and then try to open it from there
3. If none of the above fixes the problem then please send us your file, or another file that has the same problem

P

**Comment by febalestro** [comment]
I followed every instruction and now it opens :)
I think the problem was with the name of the file. Interesting enough, the same problem did not happen with a MAC (i sent the file to a person with a MAC to try and open it).

Now I know how to proceed with my windows, though. Thanks a lot! :)
