### ISSUE TITLE
Importing dxf files

### ISSUE THREAD

**Issue by techblu** [SpaceGroupUCL/depthmapX#21]
hello, good morning. I use a macbook pro 2009 and can not import files with the extension dfx. some procedure? thank you

![captura de tela 2015-03-21 as 10 26 19](https://cloud.githubusercontent.com/assets/11585608/6765208/cff49e46-cfb4-11e4-934a-3d27b655efe2.png)

**Comment by SpaceGroupUCL** [comment]
your file has to be using simple lines. no curves or circles.
Tasos
