### ISSUE TITLE
3D view

### ISSUE THREAD

**Issue by joelchet** [SpaceGroupUCL/depthmapX#22]
Hi,

I have downloaded depthmapX 0.50 and it seems promising. However, nothing is displayed when I choose the 3D view. I have checked that my video card driver is up-to-date (Intel(R) HD Graphics 4000).
Any idea why it doesn't work ? Could it be an Open GL or DirectX issue ?
Thanks in advance for your help.
Best, Joël

**Comment by varoudis** [comment]
3d View is based on OpenGL (no directX).

Can you give me more info about your machine?

Tasos
