### ISSUE TITLE
Help links not working

### ISSUE THREAD

**Issue by carolinamqrodriguez** [SpaceGroupUCL/depthmapX#23]
Dear SpaceGroup, I have been trying to open the help links below but they are not working:

http://www.vr.ucl.ac.uk/depthmap/depthmap4r1.pdf
http://www.vr.ucl.ac.uk/depthmap/tutorials/
http://www.vr.ucl.ac.uk/depthmap/scripting/

**Comment by varoudis** [comment]
Thanks. Ucl remove the old server. will update.

All tutorials can be found via: http://varoudis.github.io/depthmapX/

Tasos
