### ISSUE TITLE
URGENT! error about this program

### ISSUE THREAD

**Issue by ozlemkurtulus** [SpaceGroupUCL/depthmapX#275]
Hi, I use depthmapX 0.6 and I prepare paper for 12. space syntax symposium, but unfortunately this program gives a lot of error. 
Firstly; I don't see isovist analysis value. After applying the isovist, only the isovist area at the bottom left does not open up to other calculations.
Secondly; when I apply the global visibility feature, sometimes there is no value in some places.
finally r3 cannot calculate the visibility value.
I want you to help me with these issues because we only have 15 days to deliver the paper.
Thank you. @orange-vertex @SpaceGroupUCL 

![isovist error](https://user-images.githubusercontent.com/46162490/50456240-2e51c080-0964-11e9-87aa-48aefed4097c.jpg)

![error 2](https://user-images.githubusercontent.com/46162490/50456302-88eb1c80-0964-11e9-994e-1822ede29c45.jpg)

**Comment by orange-vertex** [comment]
Hi @ozlemkurtulus 
1) Strange that it does not. I'm sure the calculations are done for VGA and shouldn't be very slow so I might be able to enable them for single isovists in the next version. In the meantime, just do normal VGA and run isovist analysis on it. This should give you the values you need for the center of each cell.
2) I'm not sure I completely understand what you mean there but it seems that this gray area you have there is disconnected from the rest of the graph. Can you potentially send us this file to replicate this problem?
3) To get all the values for VGA (If I understand correctly) please disable "Simple Mode" (in preferences)

**Comment by ozlemkurtulus** [comment]
![error_isovist](https://user-images.githubusercontent.com/46162490/50768483-ad62c500-1291-11e9-9937-1a0ddc2190c8.JPG)

thank you for your answer.
Although the simple mode is off, the isovist analysis does not result in numerical data. I share a photo about this error.

I couldn't share the  .graph  file here. can you give me an e-mail address to share this file.

**Comment by orange-vertex** [comment]
hi @ozlemkurtulus,

The isovist issue has been fixed (https://github.com/SpaceGroupUCL/depthmapX/pull/276) and will be in the new release when that comes out.

If you still have problems with the global visibility please use a file upload service like wetransfer to upload your file (you can upload as a link, you don't have to send by email) and paste the link here.

**Comment by ozlemkurtulus** [comment]
https://we.tl/t-yQMb7elBSV

**Comment by orange-vertex** [comment]
I don't see anything strange about your file @ozlemkurtulus 
The isovists not being calculated in full is indeed a problem and you just have to wait for the next version to get the fix...
The VGA also seems normal to me...

Is there another problem or shall I close this issue?

**Comment by ozlemkurtulus** [comment]
Ok, I'll wait for the next version to full calculate the isovist area. 
There is not another problem.
When the new version of the program will be published? 

Thank you for your answer. @orange-vertex
