### ISSUE TITLE
Visualising agents movement in 3D view Mac depthmapX 6.0

### ISSUE THREAD

**Issue by LuisGoncalvesFaul** [SpaceGroupUCL/depthmapX#298]
''Hi there,

Whatever the plan I'm using I can't seem to get the 3D view to work. It had worked in previous versions of the software but it doesn't anymore. I might do something wrong but even with the tutorials, I cannot find a way to solve this issue.

The agent analysis works perfectly fine (through analysis of the visual map and so on...) but not the 3D visualization and its related features such as dropping an agent, pausing its movement, etc.

Any idea why this is ?

Many thanks in advance,

Quentin''

Hi, im reposting this , because i am having the same problem, fixed on windows pc's by picking witch graphic board opens the software, but in mac is still not opening the 3d view, i tryd also the 3dview in version 5.0 and it worked.
Simplfying, in version 6.0 for mac, what coud be reason for 3D view not working (it opens blank).

Thank you, and sory if i miss spell something.

**Comment by orange-vertex** [comment]
Hi there @LuisGoncalvesFaul, 

Can you check if this is fixed with the [new version](https://github.com/SpaceGroupUCL/depthmapX/releases/tag/v0.7.0)?

P
