### ISSUE TITLE
Feature request: Ability to display topological distance from selected convex space

### ISSUE THREAD

**Issue by ugosantana** [SpaceGroupUCL/depthmapX#321]
We already have step depth, but it would be great if we could have the ability to select a convex space and have the chromatic representation of the topological distance of each other space from this selected space

**Comment by orange-vertex** [comment]
It's not very clear to me how different that is from step-depth... Can you elaborate?

**Comment by ugosantana** [comment]
Step depth is related to visibility steps and associated to creating a grid of pixels. 

The feature I'm suggesting is related to convex spaces connected. Most of my research is using convex spaces representation of building plans. Topological distances give us the number of steps in a path from a certain space. Certain patterns of distances in building parts, can show us social relations of users. This is not directly related to visibility but connection between spaces and possible distance between users.

If you need more information, please let me know!

**Comment by orange-vertex** [comment]
There's also step-depth for convex spaces (if they are linked), just select one and Tools -> Axial / Convex / Pesh -> Step depth.

**Comment by ugosantana** [comment]
🤣 🤣 🤣 🤣 🤣 

Man, I've tested this feature sometime ago and didn't worked... then I forgot it existed!
It really works! Thanks!

Well, this was a quick solution!
