### ISSUE TITLE
depthmapX command line documentation?

### ISSUE THREAD

**Issue by 300000kms** [SpaceGroupUCL/depthmapX#324]
where can we find a documentation of the command line of the depthmapx?
thanks!

**Comment by orange-vertex** [comment]
Hi there @300000kms ,

You can find documentation in the Wiki (top centre of this page). The page for the CLI is [here](https://github.com/SpaceGroupUCL/depthmapX/wiki/Command-line-interface), though it might not be up to date. 
To see all up-to-date functionality just call help through the CLI by typing `depthmapXcli -h`

P

**Comment by blsemo** [comment]
Hi,

Have a look at the documentation at https://github.com/SpaceGroupUCL/depthmapX/blob/master/docs/commandline.md

Cheers,
Christian

On 22 August 2019 16:28:36 BST, trescientosmil <notifications@github.com> wrote:
>where can we find a documentation of the command line of the depthmapx?
>thanks!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SpaceGroupUCL/depthmapX/issues/324

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 300000kms** [comment]
thanks! works!

**Comment by RyanBirke** [comment]
Hi, 
I am having trouble following the command line documentation on a windows machine. 
Running 'depthmapXcli.exe -h' does not work from command line. Do I need to install anything else to get it to work? A c++ compiler maybe? Do I need to add to PATH?
Thanks!
Ryan

**Comment by blsemo** [comment]
Hi Ryan,

Did you see the instructions about installing the Microsoft Visual C++ runtime on the depthmapX wiki: https://github.com/SpaceGroupUCL/depthmapX/wiki/Building-and-Deployment

Cheers,
Christian

On 1 June 2020 21:27:37 BST, RyanBirke <notifications@github.com> wrote:
>Hi, 
>I am having trouble following the command line documentation on a
>windows machine. 
>Running 'depthmapXcli.exe -h' does not work from command line. Do I
>need to install anything else to get it to work? A c++ compiler maybe?
>Do I need to add to PATH?
>Thanks!
>Ryan
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/SpaceGroupUCL/depthmapX/issues/324#issuecomment-637084427

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by blsemo** [comment]
Sorry, wrong link. It's mentioned on the release page: https://github.com/SpaceGroupUCL/depthmapX/releases

On 1 June 2020 21:27:37 BST, RyanBirke <notifications@github.com> wrote:
>Hi, 
>I am having trouble following the command line documentation on a
>windows machine. 
>Running 'depthmapXcli.exe -h' does not work from command line. Do I
>need to install anything else to get it to work? A c++ compiler maybe?
>Do I need to add to PATH?
>Thanks!
>Ryan
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/SpaceGroupUCL/depthmapX/issues/324#issuecomment-637084427

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RyanBirke** [comment]
Thanks Christian! Somehow missed the cli download. Works fine now.
