### ISSUE TITLE
Visiblity Graph Analysis

### ISSUE THREAD

**Issue by pepsiadam** [SpaceGroupUCL/depthmapX#337]
When I try to run visiblity graph analysis, there is only "Visual Integration (HH)" analysis at the end of the process. But I can't reach the Visual Mean Depth, Visual Node Count, Visual Relativised Entropy at the AttributesList.
I need those, how can I solve this? I couldn't find where did I make mistake?
![xx](https://user-images.githubusercontent.com/60389879/73264501-04607280-41e4-11ea-834c-a6b999a0a26c.png)

**Comment by orange-vertex** [comment]
Hi @pepsiadam,

Yes, you need to disable "Simple mode", from the preferences (Tools -> Preferences).

Cheers,
Petros
