### ISSUE TITLE
Importing DXF

### ISSUE THREAD

**Issue by RaminDehbandi** [SpaceGroupUCL/depthmapX#341]
I was working on visual analysis of some plans and after analyzing the second one depthmap stoped importing my DXF files! even the ones it imported previously!
I tried closing the app, restarting, rebooting, redownloading but I have the same problem, can anyone help me?

**Comment by RaminDehbandi** [comment]
I tried to do that on version 0.6 (win 64). the import page last for 5sec and then depthmap disappeared!
is there anything I can do?

**Comment by orange-vertex** [comment]
Hi @RaminDehbandi,

First of all, try version [0.7.0](https://github.com/SpaceGroupUCL/depthmapX/releases/tag/v0.7.0) which is the latest. 
Then try to copy your dxf file to C:/ and import it from there

If that makes no difference then you'll have to send us one of those dxfs to test it ourselves.

Cheers,
Petros

**Comment by RaminDehbandi** [comment]
Thanks a lot, moving the files to the C:/ worked.
I think the naming of my folders was the problem, some characters of another language was used.
anyway it worked.
