### ISSUE TITLE
cli SEGMENT analysis seems not to work with  -st, "tulip"

### ISSUE THREAD

**Issue by joint-ventura** [SpaceGroupUCL/depthmapX#342]
Hi,

I´ve been trying to do some segment analysis with DepthmapXcli (in python) and cant get -st, "tulip" to work (the other types of analysis angular, metric, etc do work)... Any ideia or working example...Thanks

JVL

**Comment by orange-vertex** [comment]
Hi @joint-ventura,

What error are you getting? It should be displayed when you execute the command before all the help text.

Here's an example with the barnsbury_extended1_segment.graph from the [testdata directory](https://github.com/SpaceGroupUCL/depthmapX/tree/master/testdata):

```
 ./depthmapXcli -f barnsbury_extended1_segment.graph -o out.graph -m SEGMENT -st tulip -sr "n, 10" -srt metric -stb 1024
```

**Comment by joint-ventura** [comment]
Hi,

so sorry, it was a typo in a flag...
Everything working now, no problem.
Thanks,

JVL
