### ISSUE TITLE
relation of RRA to Integration HH values

### ISSUE THREAD

**Issue by Chrisexeter** [SpaceGroupUCL/depthmapX#347]
Do RRA and Integration HH values represent the same measure of integration, and if so what is the relationship between these values? Most of the publications I have encountered use RRA values to calculate integration, where the lower the RRA value is, then the higher the level of integration is. This appears to differ from Integration HH values, where the higher the values are, the higher integration is.

**Comment by ugosantana** [comment]
Hi there, **RRA** and **Integration HH** are the same in concept but since the bigger the value of **RRA** represents segregation (real relative asymmetry) and not integration, **Integration HH** represents better what it should be. The value is calculated like this:

**Integration HH = (1/RRA)**

**Comment by Chrisexeter** [comment]
Thank you for explaining that 🙂
