### ISSUE TITLE
VGA analysis problem with depthmapX-0.7.0_win64

### ISSUE THREAD

**Issue by archbsr** [SpaceGroupUCL/depthmapX#375]
Hello,

I can't get Visual Mean Depth (VMD) at Depthmap 0.7.0 for win64x, While my friend does the same steps at apple-book he can get the analyses. After I started the run VGA analyses, my system waits minutes it gives me only "Visual Integration". I guess it's about the operating system.

On the other hand, I do the same steps on UCL DepthMap 10, gives me VMD analyses. Perhaps because it has set up a file rather than running on .exe file. But the problem is UCL DepthMap10 hasn't got export map as .csv format. That requires me for QGIS.

How can I get VMD analyses on DepthmapX 0.7.0 version?

**Comment by blsemo** [comment]
Hi,

It's not the operating system.
Have you checked that "Simple Mode" is turned off in settings? If that is ticked, only a subset of metrics are calculated.

If that is not the problem, we'd need a bit more information.

Cheers,
Christian

On 11 September 2020 08:17:36 BST, archbsr <notifications@github.com> wrote:
>Hello,
>
>I can't get Visual Mean Depth (VMD) at Depthmap 0.0.7 for win64x, While
>my friend does the same steps at apple-book he can get the analyses.
>After I started the run VGA analyses, my system waits minutes it gives
>me only "Visual Integration". I guess it's about the operating system.
>
>On the other hand, I do the same steps on UCL DepthMap 10, gives me VMD
>analyses. Perhaps because it has set up a file rather than running on
>.exe file. But the problem is UCL DepthMap10 hasn't got export map as
>.csv format. That requires me for QGIS.
>
>How can I get VMD analyses on DepthmapX 0.0.7 version?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SpaceGroupUCL/depthmapX/issues/375

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by archbsr** [comment]
Oh. It's so simple! Thank you. It's solved.
