### ISSUE TITLE
DepthmapX is crashing when i attempt to delete an axial line or segment

### ISSUE THREAD

**Issue by ben547** [SpaceGroupUCL/depthmapX#408]
This is quite urgent so any help here would be amazing. I need to delete certain lines, but it will either immediately crash, or delete the wrong line beside it and then crash. 
Essentially I am trying to model the robustness of a road network during flood events. So I need to delete certain lines which would be flooded and then perform the various analyses, comparing it with with the pre-flood road network. So this step of deleting lines is absolutely critical.

The road network in question is the city of Hull, but the file i originally imported was much larger area of north east england. I had to crop the map in depthmapx by deleting all of the area surrounding Hull, and I did this without a problem. I then performed the angular segment analysis without problem either. But now, deleting specific lines, it crashes, and it is driving me insane!!

**Comment by blsemo** [comment]
Can you please clarify some things:
- What version of depthmapX are you using?
- What kind of map are you using? Axial map? Segment map?
- Can you provide a sample file and steps to reproduce the issue?

**Comment by ben547** [comment]
-Version 0.5b
-I am using segment map for my ASA, but I have an Axial map too and there is the same problem. 
-This is the cropped file of hull. I convert map to axial map, editable on, and then select certain lines to delete. Some will be deleted, others nothing will happen, and others if I keep trying it crashes.
[CroppedDXFfromCAD.zip](https://github.com/SpaceGroupUCL/depthmapX/files/6205516/CroppedDXFfromCAD.zip)

Thank you

**Comment by blsemo** [comment]
0.5b is fairly old, and I believe there have been fixes around deleting entities. Have you tried if the problem still happens in the latest version (0.8.0, https://github.com/SpaceGroupUCL/depthmapX/releases/tag/v0.8.0)?

**Comment by ben547** [comment]
Okay, so far that seems to have fixed it. Thank you so much!
