### ISSUE TITLE
Are the Choice and Intergration measures in the ASA equivalent to NACH and NAIN?

### ISSUE THREAD

**Issue by ben547** [SpaceGroupUCL/depthmapX#420]
Apologies if this is a silly question, but I want to produce maps showing NACH and NAIN but I cannot work out whether depthmapx does this in the ASA and simply labels it choice and integration. Or whether I need to add a new column and somehow apply the equation myself. I ask because I came across this in my reading: 
"Later, in 2012, Hillier, Yang, and Turner presented the equation for normalizing two principal measurements in space syntax: angular choice and segment integration analyses [9]. They are referred to as normalized angular choice (NACH) and
normalized angular integration (NAIN), respectively."

If they are not the same would anyone know how I would create a map showing NACH/NAIN? This is fairly urgent so really any information would be really helpful! Thank you!

**Comment by pklampros** [comment]
Hi @ben547,

No, NACh (**N**ormalised **A**ngular **Ch**oice) and NAIn (**N**ormalised **A**ngular **In**tegration) are not relabeled Choice and Integration; they are in fact completely different metrics. To create them you first need to calculate Choice and Total depth (Tools -> Segment -> Run Angular Segment Analysis..., include choice), create the two new attributes/columns (Attributes -> Add Column) and set their formulas (Attribute -> Update Column)

From the paper [1] you refer to, the equation for NACh is:
`NACh = log( ACH + 1) / log( ATD + 3)`
where ACH = Angular Choice and ATD = Angular Total Depth. Thus the formula in depthmapX needs to be:
`log(value("T1024 Choice") + 1) / log(value("T1024 Total Depth") + 3)`
assuming that you carried out Angular Tulip analysis with 1024 bins and no radius limit.
The equivalent for NAIn is:
`NAIn = NC ^ 1.2 / ATD`
where NC = Node Count and ATD = Angular Total Depth. Thus the formula for depthmapX needs to be:
`value("T1024 Node Count")^1.2 / value("T1024 Total Depth")`

Hope this helps!

[1] Hillier, W. R. G., Yang, T., & Turner, A. (2012). Normalising least angle choice in Depthmap - And how it opens up new perspectives on the global and local analysis of city space. Journal of Space Syntax, 3(2), 155–193.

**Comment by ben547** [comment]
Thank you so much! You are a Godsend. I have read through a lot of papers where they created NACH maps and detailed the formula, they just never explained how they actually used the formulae in depthmap and I could never find anywhere online how to 'update column' on attribute table! And it's so easy haha, thank you

**Comment by pklampros** [comment]
You are welcome! For future reference I transferred the details in a new file [here](https://github.com/SpaceGroupUCL/depthmapX/blob/master/docs/howdoi.md)
