### ISSUE TITLE
Can't edit the map in axial map

### ISSUE THREAD

**Issue by wan-ni-lin** [SpaceGroupUCL/depthmapX#427]
When I want to edit my map after clicking the 'Editable' button on the left, and it doesn't turn out to be editable mode with two boxes added on the line I selected. I really don't know why I've got this problem and I haven't  seen anyone had the same problem, too.

I'm just a beginner, sincerely searching for answer><
Thanks!

**Comment by pklampros** [comment]
Hi there @anniegogogo88128, axial map editing was never re-implemented for the new OpenGL map view. If you really want to edit your maps then you can open the Legacy Map view by going to Window -> Map and do it there
