### ISSUE TITLE
After running visibility graph analysis, only "Visual Integration" option is available in Attributes list

### ISSUE THREAD

**Issue by Apurba-Sen** [SpaceGroupUCL/depthmapX#430]
Hi,
I am trying to run a visibility graph analysis of a floor plan (drawn in "ft-in" scale). But after clicking  the option "Run visibility graph analysis" only one attribute (Visual Integration-HH) is visible. Attributes like Visual mean depth, Visual node count, Visual entropy etc. are missing in my case. What should I do to run the analysis?

I am using DepthmapX-0.8.0 and Windows 10.

Thank you

![Issue](https://user-images.githubusercontent.com/90888930/148811460-8931a6ca-12e4-4d51-b035-1057623b75e1.JPG)
.

**Comment by pklampros** [comment]
Hi @Apurba-Sen,

Please disable simple mode and try again. You can find the toggle in the settings (Tools -> Options)

**Comment by Apurba-Sen** [comment]
Hi Petros Koutsolampros,

Thank you for yor help. Such a simple solution of a problem that was
driving me crazy.

Thank you once again.

**Comment by drunk3nb0at** [comment]
Thanks for this answer! I found it helpful too, and if you are using macOS, you can find the simple mode option in "preference"(shortcut cmd+,)
