### ISSUE TITLE
Depthmap X crashes when importing dxf file

### ISSUE THREAD

**Issue by Aittam93** [SpaceGroupUCL/depthmapX#431]
I'm totally new with Depthmap. Following the tutorial in spacesyntax.online I downloaded the dxf tutorial file. Every time I import it, the application crashes and closes

**Comment by pklampros** [comment]
Hi @Aittam93,

If you are using the latest version (v0.8.0) and on windows, try moving the dxf file to C:\ and then opening it. If it doesn't work please point us to the DXF file for us to test it.
