### ISSUE TITLE
How do I type in the NAIN formula for a new column?

### ISSUE THREAD

**Issue by Intuos5** [SpaceGroupUCL/depthmapX#432]
For a regular root formula, I type "sqrt(x)", How should I do this for NAIN (Normalised Angular Integration) where the root is not squared?
![afbeelding](https://user-images.githubusercontent.com/63149655/154313960-b101fa02-46a6-43ed-a7f1-7d0dcac81078.png)

**Comment by Intuos5** [comment]
Nevermind, it should be: (value("T1024 Node Count R200 metric")^(1/1.2))/(value("T1024 Angular Total Depth R200 metric")+2)

**Comment by pklampros** [comment]
Hey @Intuos5,

Glad you found it, but can you point me to where you found that formula? It seems wrong to me in many ways...

It doesn't follow the original formula from Hillier et al. (2012) in page 165:
`NC^1.2/TD`
or the one adjusted for Depthmap from pages 191/192
`(NC + 2)^1.2/TD`

Instead yours is:
`NC^(1/1.2)/(TD + 2)`

**Comment by Intuos5** [comment]
@pklampros, thanks for the reaction, I found it in van Nes, A., & Yamu, C. (2021). Introduction to space syntax in urban studies. in page 97. Though the same authors list it differently in Bill Hillier's Legacy: Space Syntax—A Synopsis of Basic Concepts, Measures, and Empirical Application (2021) on page 13:
![afbeelding](https://user-images.githubusercontent.com/63149655/154338468-ee90b326-9b46-4588-a1ba-13e7c78e809a.png)

Also, the formula is shown in the Space Syntax for Dummies guide, item 23, see https://raw.githubusercontent.com/SpaceGroupUCL/depthmapX/master/docs/DepthmapManualForDummies_v20_short.pdf

Offtopic:
1. Could you also point me to what Segment Length Weight (SLW) does and how it works? It seems to me that it compensates for longer segments, but since I there are quite a lot of additional points in OSM maps that I don't want to edit, I'm not sure how reliable the results would be. 
2. How does metric choice differ from Choice? Other than that choice is based on angular deviation, whereas metric is based on how often a particular line is encountered from any point in the network to any other point with search radius X. The results are almost the same for my study on Florence r=800m. But what does metric choice signify in practical terms?
