### ISSUE TITLE
betweeness clustering coefficient

### ISSUE THREAD

**Issue by LAOUAR** [SpaceGroupUCL/depthmapX#435]
Hi everyone,
Please, i ve issues with VGA, i want to get : control controllability and clustering coeficient, betweeness. 
1.i ve set a grid (20)
2.tool-visibility-make visibility graph
3.run visibility graph analysis
4.calculate visibility relationship; i selected both of - include global and- local measures,- i put radius n. But unfortunately i didnt get any one of the abovementioned measures except visual integration. (i ve used depthmapx the latest version in github.)
Please could any one answer me. Thank you.

**Comment by blsemo** [comment]
Have you tried turning off simple mode in the settings menu?

29 Aug 2022 22:27:03 LAOUAR ***@***.***>:

**Comment by LAOUAR** [comment]
Thank you very much Christian Sailor, it works now, i am really very grateful for that. Please i ve another question about betweenness how can i calculate it or get it in VGA. Thank you have a good day.

**Comment by pklampros** [comment]
Betweenness is not calculated for VGA (it doesn't make much sense) in depthmapX. You best bet is to export the VGA connections and calculate it yourself in a different app, or in python using a dedicated library.

**Comment by LAOUAR** [comment]
Thank you very much Petros Koutsolampros for your answer, it's really kinfd from you. However, i am not very familiar with python, can you give me more informations about how can i  calculate it from vga connections, because i am working in GIS file and i want a grid map of betwenness so i can join it with other parameters of my study. Thank you in advance.

**Comment by pklampros** [comment]
@LAOUAR this is a particularly broad question.... In short, you export the VGA connections from depthmapX, import them into Python to make a graph (perhaps with the igraph library?), and then calculate Betweenness using the same graph library.

**Comment by LAOUAR** [comment]
Is it possible in R? Thank you very much

**Comment by pklampros** [comment]
It certainly is, look at [igraph for r](https://igraph.org/r/), and [betweenness using igraph in R](https://igraph.org/r/doc/betweenness.html)

**Comment by LAOUAR** [comment]
@pklampros thanks a lot, i am so grateful.

**Comment by LAOUAR** [comment]
Hi @pklampros , please in which format can i import VGA to Igraph R? Thank you very much.
Best Regards,
Dounia Laouar
