### ISSUE TITLE
DepthmapX question

### ISSUE THREAD

**Issue by rubie023** [SpaceGroupUCL/depthmapX#439]
Hi im korea Student.
I am using this website for the first time, and I'm not sure if I'm writing this kind of post in the right way. my bad :(

<Visibility graphs>
VGA map - Ref Number, Connectivity, point first moment, point second moment

<Shape Graphs>
All-Line Map - Ref Number, Connectivity, Line Length, entropy,
Integration [HH], [P-value], [Tekl], Intensity, Harmonic Mean Depth, Mean Depth, Node Count, Relativised Entropy

I need a brief explanation of what each data title above means or what it refers to. Can you help me with that?

Or is there a manual that has a description of it?

I couldn't find descriptions of each feature in the already distributed manual

Help me plz

**Comment by maurimartins** [comment]
Hi Rubie023,

Perhaps you can familiarize yourself with using some of these parameters in:
Al-Sayed, K (2014) *Space* *Syntax* *methodology*.
<https://search2.ucl.ac.uk/s/redirect?collection=ucl-discovery&url=http%3A%2F%2Fdiscovery.ucl.ac.uk%2F1415080%2F&auth=pKJjDMlkn%2BPWtDCT%2BHappQ&profile=_default&rank=1&query=Space+Syntax+methodology>
A
teaching guide for the MRes/MSc *Space* *Syntax* course (version 5).
Bartlett School of Architecture, UCL: London, UK. (2014)

To consult brief descriptions, there is a glossary organized at Online
Training Platform by Space Syntax Network: https://www.spacesyntax.online/

I hope this helps,

Mauricio

**Comment by rubie023** [comment]
1. 
<https://search2.ucl.ac.uk/s/redirect?collection=ucl-discovery&url=http%3A%2F%2Fdiscovery.ucl.ac.uk%2F1415080%2F&auth=pKJjDMlkn%2BPWtDCT%2BHappQ&profile=_default&rank=1&query=Space+Syntax+methodology>

Item Removed
You seem to be attempting to access an item that has been removed from the repository.

2.
<https://www.spacesyntax.online/>

There has been a critical error on this website.
[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)

I can't see it.

It's too bad I can't see you
im sad T^T 

![001](https://user-images.githubusercontent.com/128459637/226762417-8a7e2bc7-d066-401e-ba35-c9a55472e889.PNG)
![002](https://user-images.githubusercontent.com/128459637/226762427-a88bc8a8-2502-4bb1-a5e1-b9878ed145ab.PNG)

**Comment by pklampros** [comment]
You can find explanations of most of the VGA metrics in section 4.3 (page 123) in [Koutsolampros, Petros; (2021) Human behaviour in office environments. Finding patterns of activity and spatial configuration in large workplace datasets. Doctoral thesis (Ph.D), UCL (University College London). ](https://discovery.ucl.ac.uk/id/eprint/10122284/) or in a shorter (less developed) form in [Koutsolampros, P; Sailer, K; Varoudis, T; Haslem, R; (2019) Dissecting Visibility Graph Analysis: The metrics and their role in understanding workplace human behaviour. In: Proceedings of the 12th International Space Syntax Symposium (12 SSS). International Space Syntax Symposium: Beijing, China.](https://discovery.ucl.ac.uk/id/eprint/10073528/).

**Comment by rubie023** [comment]
ty :)
