### ISSUE TITLE
crash! help！！

### ISSUE THREAD

**Issue by TANKUNG7908** [SpaceGroupUCL/depthmapX#440]
Hello. After few seconds it‘s crashes when I wanna do anything. 
My depthmapX keeps crashing even with any simple operations. 
Any suggestion why this is happening? I have 16 GB ram on Window11 64-bit. Thank you.

🥹PS：If such a low-level error cannot be resolved, I will have no confidence in the software🥹

**Comment by drunk3nb0at** [comment]
hi, maybe you can try to download a different version of depthmapX! From my experience, this software is not very stable, so you maybe need to try and error a lot/ pivot your work.

**Comment by pklampros** [comment]
The software can sometimes not handle files when they are placed in a folder with non English characters. Try moving your file to C:/ and see if it works from there
