### ISSUE TITLE
Cannot run on MacOS. Error: "depthmapX cannot be opened because the developer cannot be verified"

### ISSUE THREAD

**Issue by giannastavroulaki** [SpaceGroupUCL/depthmapX#452]
Hello, I tried to open “depthmapX” on my Mac. I got this: 
'cannot be opened because the developer cannot be verified.' 

How can I solve this?

Thank you,
Gianna

**Comment by chraibi** [comment]
Go to Privacy & Security and then open depthmapX anyway!

![Image](https://github.com/user-attachments/assets/b7acfdfd-2ddd-4346-9fdd-5179402cd892)
